# This is a basic workflow to help you get started with Actions

name: user-input
on:
  workflow_dispatch:
    inputs:
      message:
        description: not harcoded message
        required:  true
        default: "hello from homelab"
        type: string
jobs:
  simple-job:
    runs-on: ubuntu-latest
    steps:
      - name: print user message
        run:  echo ${{ github.event.inputs.message }}
        shell: bash
        
        
    
        
    

